### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by smiller171**
"It's" is a contraction. "Its" is a possessive.

### CODE REVIEW

**Review by sblack4 — APPROVED** [review]
:shipit: I was talking to @cdaniluk and I think we're going to take the tags module out as a submodule of our modules. I kinds like including it, if only for the DLs, but don't really care one way or another

**Comment by cdaniluk** [comment]
> :shipit: I was talking to @cdaniluk and I think we're going to take the tags module out as a submodule of our modules. I kinds like including it, if only for the DLs, but don't really care one way or another

I don't feel terribly strongly about this. We wouldn't be the only company dropping a tagging submodule in our modules if we kept it. But I will say my current process is to create a repo off of this template and then immediately delete the tags module. Followed by removing it from `outputs.tf` after my first attempt to test my module.

**Review by cdaniluk — APPROVED** [review]

**Comment by sblack4** [comment]
The check is failing because it's trying to update the description in the README to match the updated output description

**Comment by smiller171** [comment]
Well that's annoying. That means it's currently impossible to make changes in the GitHub UI

I'm gonna extend the GitHub actions to actually commit any automatic changes like this in PRs

**Comment by smiller171** [comment]
but I agree with pulling out the tags module. That should be handled entirely in the parent (as I think I argued initially)

**Pull request closed without merging**
